from datetime import datetime
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, validator


class BaseSchema(BaseModel):
    model_config = ConfigDict(
        from_attributes=True,
        use_enum_values=True,
        extra="ignore",
    )


class BaseData(BaseSchema):
    model_config = ConfigDict(
        from_attributes=True,
        use_enum_values=True,
        extra="ignore",
    )

    public_id: str

    @property
    def __topic__(self):
        raise NotImplementedError("override this property")

    @property
    def __event_name__(self):
        raise NotImplementedError("override this property")

    @property
    def __event_version__(self):
        raise NotImplementedError("override this property")


class Message[T: BaseData | dict](BaseSchema):
    producer: str
    data: T

    # Autogenerated fields
    event_id: str = Field(default_factory=lambda: str(uuid4()))
    event_time: str = Field(default_factory=lambda: datetime.now().isoformat())
    event_name: str = ""
    event_version: int = 0

    @validator("event_name", pre=False, always=True)
    def set_event_name(cls, v, values, **kwargs):
        if v:
            return v
        return values["data"].__event_name__

    @validator("event_version", pre=False, always=True)
    def set_event_version(cls, v, values, **kwargs):
        if v:
            return v

        return values["data"].__event_version__
