# Generated by Django 5.0 on 2024-03-10 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('done', 'Done')], default='new', max_length=255)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reward', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
