version: '3'


# Custom network on my server, adjust.
networks:
  default:
    name: server-private
    external: true

# Todo: Add volumes

services:

  # =============== Main Services ===============

  # ======= Auth Service =======
  service-auth:
    image: sjc.vultrcr.com/buftio/aa-service-auth:latest
    depends_on:
      - postgres-auth
      - broker
    environment:
      - DATABASE_URL=postgres://postgres@postgres-auth/postgres
      - KAFKA_BROKER=broker:9092
      - KAFKA_GROUP_ID=auth
    env_file:
      - .env.auth

  postgres-auth:
    image: postgres:16.1
    volumes:
      - ./data/postgres-auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  # ======= Tracker Service =======
  service-tracker:
    image: sjc.vultrcr.com/buftio/aa-service-tracker:latest
    depends_on:
      - postgres-tracker
      - broker
    environment:
      - DATABASE_URL=postgres://postgres@postgres-tracker/postgres
      - KAFKA_BROKER=broker:9092
      - AUTH_VALIDATE_TOKEN_HOST=http://service-auth:8000/oauth/introspect/
      - KAFKA_GROUP_ID=tracker
    env_file:
      - .env.tracker

  consumer-tracker:
    image: sjc.vultrcr.com/buftio/aa-service-tracker:latest
    command: ./manage.py consumer
    depends_on:
      - postgres-tracker
      - broker
    environment:
      - DATABASE_URL=postgres://postgres@postgres-tracker/postgres
      - KAFKA_BROKER=broker:9092
      - KAFKA_GROUP_ID=tracker
    env_file:
      - .env.tracker

  postgres-tracker:
    image: postgres:16.1
    volumes:
      - ./data/postgres-tracker:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  # ======== Billing Service =======
  service-billing:
    image: sjc.vultrcr.com/buftio/aa-service-billing:latest
    depends_on:
      - postgres-billing
      - broker
    environment:
      - DATABASE_URL=postgres://postgres@postgres-billing/postgres
      - KAFKA_BROKER=broker:9092
      - AUTH_VALIDATE_TOKEN_HOST=http://service-auth:8000/oauth/introspect/
      - KAFKA_GROUP_ID=billing
    env_file:
      - .env.billing

  consumer-billing:
    image: sjc.vultrcr.com/buftio/aa-service-billing:latest
    command: ./manage.py consumer
    depends_on:
      - postgres-billing
      - broker
    environment:
      - DATABASE_URL=postgres://postgres@postgres-billing/postgres
      - KAFKA_BROKER=broker:9092
      - KAFKA_GROUP_ID=billing
    env_file:
      - .env.billing

  postgres-billing:
    image: postgres:16.1
    volumes:
      - ./data/postgres-billing:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  # ======== Analytics Service =======
  service-analytics:
    image: sjc.vultrcr.com/buftio/aa-service-analytics:latest
    depends_on:
      - postgres-analytics
      - broker
    environment:
      - DATABASE_URL=postgres://postgres@postgres-analytics/postgres
      - KAFKA_BROKER=broker:9092
      - AUTH_VALIDATE_TOKEN_HOST=http://service-auth:8000/oauth/introspect/
      - KAFKA_GROUP_ID=analytics
    env_file:
      - .env.analytics

  consumer-analytics:
    image: sjc.vultrcr.com/buftio/aa-service-analytics:latest
    command: ./manage.py consumer
    depends_on:
      - postgres-analytics
      - broker
    environment:
      - DATABASE_URL=postgres://postgres@postgres-analytics/postgres
      - KAFKA_BROKER=broker:9092
      - KAFKA_GROUP_ID=analytics
    env_file:
      - .env.analytics

  postgres-analytics:
    image: postgres:16.1
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  # ======== Frontend =======

  frontend:
    image: sjc.vultrcr.com/buftio/aa-frontend:latest
    depends_on:
      - postgres-frontend
    environment:
      - DATABASE_URL=postgres://postgres@postgres-frontend/postgres
      - PUBLIC_AUTH_BACKEND_URL=https://auth.aa.buft.io
      - PUBLIC_TRACKER_BACKEND_URL=https://tracker.aa.buft.io
      - PUBLIC_BILLING_BACKEND_URL=https://billing.aa.buft.io
      - PUBLIC_ANALYTICS_BACKEND_URL=https://analytics.aa.buft.io
    env_file:
      - .env.frontend

  postgres-frontend:
    image: postgres:16.1
    volumes:
      - ./data/postgres-frontend:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  # =============== Supplementary Services ===============

  # Kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
