# Generated by Django 5.0 on 2024-02-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
